[source]
url = "https://www.youtube.com/watch?v=FEm6oPhl2uo"
video_id = "FEm6oPhl2uo"
title = "[스타트악보] Hayley Williams - Dead Horse"
uploader = "스타트드럼 - START DRUM"
duration = 196.0

[models]
separation = ""

[grid]
meter = ""
tempo_multiplier = 0
downbeat_rotation = -1
