[source]
url = "https://www.youtube.com/watch?v=axGGBn8d0KI"
video_id = "axGGBn8d0KI"
title = "1612 - Vulfpeck - Drum Cover"
uploader = "Brian Daggett Drums"
duration = 244.0

[models]
separation = ""

[grid]
meter = ""
tempo_multiplier = 0
downbeat_rotation = -1
