/// <reference types="vite/client" />

// The song catalogue, generated by plugins/ableton.ts from songs/*/song.toml.
declare module 'virtual:songs' {
  export interface Section {
    name: string;
    /** 1-based and inclusive. */
    start_bar: number;
    end_bar: number;
  }
  export interface SongMeta {
    slug: string;
    title: string;
    /** MIDI key -> instrument name (kick, snare, hihat_closed, ...). */
    map: Record<number, string>;
    /** The `[[section]]` blocks, in the order they are written. */
    sections: Section[];
    /** Those blocks as one string, so a take can be pinned to them. */
    sectionsHash: string;
    author?: { als: string; track?: string };
    /**
     * Which untracked media is on disk: `mix` is the clock (without it the
     * song cannot play), `video` the picture the notation sits over.
     */
    media: { mix: boolean; video: boolean };
  }
  const songs: SongMeta[];
  export default songs;
}

// kit.toml's `[input]`, generated by plugins/practice.ts: what the module you
// hit sends. Not the same numbering as a song's `[midi_map]` -- see kit.toml.
declare module 'virtual:kit' {
  export interface KitInput {
    /** Substring of the MIDI port name to open by default. */
    port: string;
    /** Module note number -> instrument name. */
    note: Record<number, string>;
    /** Groups of instruments that are one drum in different states. */
    same_drum: string[][];
  }
  /** How the bank is played: taste, read live from kit.toml's [sampler]. */
  export interface KitSampler {
    /** Groups of articulations that cut each other off. */
    choke: string[][];
    /** Per-instrument trim in dB. */
    trim: Record<string, number>;
    /** Articulations that ring long enough to need cutting off. */
    ring: string[];
  }

  /** One velocity layer: the velocity it was rendered at, and its takes. */
  export interface BankLayer {
    velocity: number;
    peak: number;
    /** Paths under kit/samples/, served at /kit/samples/<file>. */
    files: string[];
  }

  export interface BankArticulation {
    instrument: string;
    /** The one picked when nothing asks for a particular strike. */
    default: boolean;
    stereo: boolean;
    /** Quietest first. */
    layers: BankLayer[];
  }

  /** What `drums kit-bake` rendered, from kit/kit.lock.json. */
  export interface Bank {
    name: string;
    sampleRate: number;
    gain: number;
    renderedAt: string;
    articulations: Record<string, BankArticulation>;
  }

  const input: KitInput;
  export default input;
  export const sampler: KitSampler;
  /** Null when no kit has been baked -- which is not the same as an empty one. */
  export const bank: Bank | null;
}
