/// <reference types="vite/client" />

// The song catalogue, generated by plugins/ableton.ts from songs/*/song.toml.
declare module 'virtual:songs' {
  export interface SongMeta {
    slug: string;
    title: string;
    /** MIDI key -> instrument name (kick, snare, hihat_closed, ...). */
    map: Record<number, string>;
    author?: { als: string; track?: string };
  }
  const songs: SongMeta[];
  export default songs;
}
