[source]
url = "https://www.youtube.com/watch?v=nuJzia4ypiw"
video_id = "nuJzia4ypiw"
title = "Song 2 - Blur DRUM COVER"
uploader = "알려드럼"
duration = 133.0

[models]
separation = ""

[grid]
meter = ""
tempo_multiplier = 0
downbeat_rotation = -1
